version: '3.8'
services:
  frontend:
    build:
      context: ../frontend
      target: builder # Hot Reload Placeholder support in dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    volumes:
      - ../backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
