import { Router } from 'express';
import { healthCheck } from '../controllers/health.controller';
import courseRoutes from './course.routes';
import semesterRoutes from './semester.routes';
import schoolRoutes from './school.routes';
import departmentRoutes from './department.routes';
import dashboardRoutes from './dashboard.routes';
import explorerRoutes from './explorer.routes';
import publicStatsRoutes from './publicStats.routes';
import helpRoutes from './help.routes';
import supportRoutes from './support.routes';
import legalRoutes from './legal.routes';
import aiRoutes from './ai.routes';
import semanticSearchRoutes from './semanticSearch.routes';
import subjectRoutes from './subject.routes';
import searchRoutes from './search.routes';
import adminRoutes from './admin.routes';
import communityRoutes from './community.routes';
import paperRoutes from './paper.routes';
import duplicateRoutes from './duplicate.routes';
import moderationRoutes from './moderation.routes';
import downloadRoutes from './download.routes';
import viewerRoutes from './viewer.routes';
import libraryRoutes from './library.routes';
import reportRoutes from './report.routes';
import recommendationRoutes from './recommendation.routes';
import analyticsRoutes from './analytics.routes';
import notificationRoutes from './notification.routes';
import rbacRoutes from './rbac.routes';
import settingsRoutes from './settings.routes';
import auditRoutes from './audit.routes';
import backupRoutes from './backup.routes';

const router = Router();

// v1 API Routes
router.get('/health', healthCheck);

// Mount module routers here
router.use('/courses', courseRoutes);
router.use('/semesters', semesterRoutes);
router.use('/schools', schoolRoutes);
router.use('/departments', departmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/public/papers', explorerRoutes);
router.use('/public', publicStatsRoutes);
router.use('/help', helpRoutes);
router.use('/support', supportRoutes);
router.use('/legal', legalRoutes);
router.use('/ai', aiRoutes);
router.use('/semantic-search', semanticSearchRoutes);
router.use('/subjects', subjectRoutes);
router.use('/search', searchRoutes);
router.use('/admin', adminRoutes);
router.use('/community', communityRoutes);
router.use('/question-papers', paperRoutes);
router.use('/duplicates', duplicateRoutes);
router.use('/moderation', moderationRoutes);
router.use('/downloads', downloadRoutes);
router.use('/viewer', viewerRoutes);
router.use('/library', libraryRoutes);
router.use('/reports', reportRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/rbac', rbacRoutes);
router.use('/settings', settingsRoutes);
router.use('/audit', auditRoutes);
router.use('/backups', backupRoutes);

export default router;
