import { Router } from 'express';
import { healthCheck } from '../controllers/health.controller';
import authRoutes from '../features/auth/routes/auth.routes';
import courseRoutes from './course.routes';
import semesterRoutes from './semester.routes';
import schoolRoutes from './school.routes';
import departmentRoutes from './department.routes';
import dashboardRoutes from './dashboard.routes';
import explorerRoutes from './explorer.routes';
import publicStatsRoutes from './publicStats.routes';
import helpRoutes from './help.routes';
import supportRoutes from './support.routes';
import legalRoutes from './legal.routes';
import aiRoutes from './ai.routes';
import aiChatRoutes from './aiChat.routes';
import semanticSearchRoutes from './semanticSearch.routes';
import analysisRoutes from './analysis.routes';
import studyPlannerRoutes from './studyPlanner.routes';
import revisionRoutes from './revision.routes';
import ocrRoutes from './ocr.routes';
import ragRoutes from './rag.routes';
import agentRoutes from './agent.routes';
import facultyAiRoutes from './facultyAi.routes';
import executiveRoutes from './executive.routes';
import oauthRoutes from './oauth.routes';
import mfaRoutes from './mfa.routes';
import securityRoutes from '../features/security/routes/security.routes';
import preferencesRoutes from '../features/preferences/routes/preferences.routes';
import onboardingRoutes from '../features/onboarding/routes/onboarding.routes';
import accountRoutes from '../features/account/routes/account.routes';
import adoptionRoutes from '../features/adoption/routes/adoption.routes';
import subjectRoutes from './subject.routes';
import searchRoutes from './search.routes';
import adminRoutes from './admin.routes';
import communityRoutes from './community.routes';
import paperRoutes from './paper.routes';
import duplicateRoutes from './duplicate.routes';
import moderationRoutes from './moderation.routes';
import downloadRoutes from '../features/downloads/routes/download.routes';
import bookmarkRoutes from '../features/bookmarks/routes/bookmark.routes';
import newLibraryRoutes from '../features/library/routes/library.routes';
import collectionRoutes from '../features/collections/routes/collection.routes';
import versionRoutes from '../features/versioning/routes/version.routes';
import integrityRoutes from '../features/integrity/routes/integrity.routes';
import aiMetadataRoutes from '../features/ai-metadata/routes/ai-metadata.routes';
import repositoryAnalyticsRoutes from '../features/repository-analytics/routes/analytics.routes';
import migrationRoutes from '../features/repository-migration/routes/migration.routes';
import questionExtractionRoutes from '../features/question-extraction/routes/extraction.routes';
import bloomRoutes from '../features/bloom/routes/bloom.routes';
import topicRoutes from '../features/topic-mapping/routes/topic.routes';
import difficultyRoutes from '../features/difficulty/routes/difficulty.routes';
import marksRoutes from '../features/marks-analysis/routes/marks.routes';
import patternRoutes from '../features/pattern-analysis/routes/pattern.routes';
import trendRoutes from '../features/trends/routes/trend.routes';
import insightRoutes from '../features/ai-insights/routes/insight.routes';
import facultyRoutes from '../features/faculty-analytics/routes/faculty.routes';
import studentRoutes from '../features/student-insights/routes/student.routes';
import qualityRoutes from '../features/ai-quality/routes/quality.routes';
import reprocessingRoutes from '../features/reprocessing/routes/reprocessing.routes';
import operationsRoutes from '../features/ai-operations/routes/operations.routes';
import bulkRoutes from '../features/bulk-analysis/routes/batch.routes';
import gatewayRoutes from '../features/ai-gateway/routes/gateway.routes';
import viewerRoutes from './viewer.routes';
import libraryRoutes from './library.routes';
import reportRoutes from './report.routes';
import recommendationRoutes from './recommendation.routes';
import analyticsRoutes from './analytics.routes';
import notificationRoutes from './notification.routes';
import rbacRoutes from './rbac.routes';
import settingsRoutes from './settings.routes';
import auditRoutes from './audit.routes';
import backupRoutes from './backup.routes';
import authAdminRoutes from '../features/auth-admin/routes/auth-admin.routes';
import academicRoutes from '../features/academic/routes/academic.routes';
import schoolManagementRoutes from '../features/academic/routes/school.routes';
import departmentManagementRoutes from '../features/academic/routes/department.routes';
import courseManagementRoutes from '../features/academic/routes/course.routes';
import semesterManagementRoutes from '../features/academic/routes/semester.routes';
import subjectManagementRoutes from '../features/academic/routes/subject.routes';
import hierarchyNavigationRoutes from '../features/academic/routes/hierarchy.routes';
import academicSearchRoutes from '../features/academic/routes/search.routes';
import importExportRoutes from '../features/academic/routes/import-export.routes';
import uploadRoutes from '../features/upload/routes/upload.routes';
import metadataRoutes from '../features/metadata/routes/metadata.routes';
import pdfViewerRoutes from '../features/pdf-viewer/routes/pdf-viewer.routes';

const router = Router();

// v1 API Routes
router.get('/health', healthCheck);

// Core Auth Routes
router.use('/auth', authRoutes);

// Mount module routers here
router.use('/courses', courseRoutes);
router.use('/semesters', semesterRoutes);
router.use('/schools', schoolRoutes);
router.use('/departments', departmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/public/papers', explorerRoutes);
router.use('/public', publicStatsRoutes);
router.use('/help', helpRoutes);
router.use('/support', supportRoutes);
router.use('/legal', legalRoutes);
router.use('/ai', aiRoutes);
router.use('/ai-chat', aiChatRoutes);
router.use('/semantic-search', semanticSearchRoutes);
router.use('/analysis', analysisRoutes);
router.use('/study-planner', studyPlannerRoutes);
router.use('/revision', revisionRoutes);
router.use('/ocr', ocrRoutes);
router.use('/rag', ragRoutes);
router.use('/agents', agentRoutes);
router.use('/faculty-ai', facultyAiRoutes);
router.use('/executive', executiveRoutes);
router.use('/auth/oauth', oauthRoutes);
router.use('/auth/mfa', mfaRoutes);
router.use('/security', securityRoutes);
router.use('/preferences', preferencesRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/account', accountRoutes);
router.use('/adoption', adoptionRoutes);
router.use('/subjects', subjectRoutes);
router.use('/search', searchRoutes);
router.use('/admin', adminRoutes);
router.use('/community', communityRoutes);
router.use('/question-papers', paperRoutes);
router.use('/duplicates', duplicateRoutes);
router.use('/moderation', moderationRoutes);
router.use('/downloads', downloadRoutes);
router.use('/bookmarks', bookmarkRoutes);
router.use('/library-new', newLibraryRoutes);
router.use('/collections', collectionRoutes);
router.use('/moderation-queue', moderationRoutes);
router.use('/versions', versionRoutes);
router.use('/integrity', integrityRoutes);
router.use('/ocr', ocrRoutes);
router.use('/ai-metadata', aiMetadataRoutes);
router.use('/repository-analytics', repositoryAnalyticsRoutes);
router.use('/migration', migrationRoutes);
router.use('/analysis', analysisRoutes);
router.use('/question-extraction', questionExtractionRoutes);
router.use('/bloom', bloomRoutes);
router.use('/topic-mapping', topicRoutes);
router.use('/difficulty', difficultyRoutes);
router.use('/marks-analysis', marksRoutes);
router.use('/pattern-analysis', patternRoutes);
router.use('/trend-analysis', trendRoutes);
router.use('/ai-insights', insightRoutes);
router.use('/faculty-analytics', facultyRoutes);
router.use('/student-insights', studentRoutes);
router.use('/ai-quality', qualityRoutes);
router.use('/reprocessing', reprocessingRoutes);
router.use('/ai-operations', operationsRoutes);
router.use('/bulk-analysis', bulkRoutes);
router.use('/ai-gateway', gatewayRoutes);
router.use('/viewer', viewerRoutes);
router.use('/library', libraryRoutes);
router.use('/reports', reportRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/rbac', rbacRoutes);
router.use('/settings', settingsRoutes);
router.use('/audit', auditRoutes);
router.use('/backups', backupRoutes);
router.use('/auth-admin', authAdminRoutes);
router.use('/academic', academicRoutes);
router.use('/schools', schoolManagementRoutes);
router.use('/departments', departmentManagementRoutes);
router.use('/courses', courseManagementRoutes);
router.use('/semesters', semesterManagementRoutes);
router.use('/subjects', subjectManagementRoutes);
router.use('/navigation', hierarchyNavigationRoutes);
router.use('/search', academicSearchRoutes);
router.use('/ops', importExportRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/papers', paperRoutes);
router.use('/uploads', uploadRoutes);
router.use('/metadata', metadataRoutes);
router.use('/pdf', pdfViewerRoutes);

export default router;
