apiVersion: v1
kind: Service
metadata:
  name: backend-api-svc
  namespace: cuhp-prod
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
