export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
  INACTIVE = 'INACTIVE'
}

export enum UserRole {
  STUDENT = 'STUDENT',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
}

export enum AuthAction {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
  FAILED_LOGIN = 'FAILED_LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  MFA_FAILED = 'MFA_FAILED',
  MFA_SUCCESS = 'MFA_SUCCESS',
  PROVIDER_LINKED = 'PROVIDER_LINKED',
  PROVIDER_UNLINKED = 'PROVIDER_UNLINKED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  DEVICE_REVOKED = 'DEVICE_REVOKED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED'
}
