import React, { useState, useEffect } from 'react';
import { useMFASetup, useMFAEnable } from '../hooks/useMFA';
import { QRCodeCard } from './QRCodeCard';
import { VerificationCodeInput } from './VerificationCodeInput';
import { BackupCodes } from './BackupCodes';
import { motion } from 'framer-motion';

interface MFASetupWizardProps {
  onCancel: () => void;
  onSuccess: () => void;
}

export const MFASetupWizard: React.FC<MFASetupWizardProps> = ({ onCancel, onSuccess }) => {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [setupData, setSetupData] = useState<{ secret: string; qrCode: string } | null>(null);
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  
  const { mutate: initiateSetup } = useMFASetup();
  const { mutate: enableMfa, isPending: isEnabling } = useMFAEnable();

  useEffect(() => {
    initiateSetup(undefined, {
      onSuccess: (data) => setSetupData(data),
    });
  }, [initiateSetup]);

  const handleVerify = (token: string) => {
    enableMfa(token, {
      onSuccess: (data) => {
        setBackupCodes(data.backupCodes);
        setStep(3);
      }
    });
  };

  if (!setupData && step === 1) {
    return <div className="text-center py-8">Initializing secure connection...</div>;
  }

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div className="flex gap-2">
          {[1, 2, 3].map(i => (
            <div key={i} className={`h-2 w-12 rounded-full \${step >= i ? 'bg-primary' : 'bg-gray-200 dark:bg-gray-700'}`} />
          ))}
        </div>
        <button onClick={onCancel} className="text-sm font-medium text-muted-foreground hover:text-foreground">Cancel Setup</button>
      </div>

      <motion.div
        key={step}
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.3 }}
      >
        {step === 1 && setupData && (
          <div className="space-y-6">
            <h3 className="text-xl font-bold">1. Scan the QR Code</h3>
            <p className="text-muted-foreground">Open your authenticator app (like Google Authenticator or Authy) and scan the QR code below.</p>
            <QRCodeCard qrCode={setupData.qrCode} secret={setupData.secret} />
            <div className="flex justify-end">
              <button onClick={() => setStep(2)} className="px-6 py-2.5 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors">
                Next Step
              </button>
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-6">
            <h3 className="text-xl font-bold">2. Verify Code</h3>
            <p className="text-muted-foreground">Enter the 6-digit code generated by your authenticator app to verify the setup.</p>
            <div className="py-8">
              <VerificationCodeInput onComplete={handleVerify} isLoading={isEnabling} />
            </div>
            <div className="flex justify-between">
              <button onClick={() => setStep(1)} className="px-6 py-2.5 bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded-lg font-medium hover:bg-gray-300 dark:hover:bg-gray-700 transition-colors">
                Back
              </button>
            </div>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-6">
            <h3 className="text-xl font-bold text-success">3. Setup Complete!</h3>
            <p className="text-muted-foreground">Two-factor authentication is now enabled. Save these backup codes in a secure place. They can be used if you lose access to your device.</p>
            <BackupCodes codes={backupCodes} />
            <div className="flex justify-end mt-6">
              <button onClick={onSuccess} className="px-6 py-2.5 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors">
                I have saved my codes
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
};
