export const EMAIL_VERIFICATION_CONSTANTS = {
  MESSAGES: {
    EMAIL_REQUIRED: 'Email address is required.',
    EMAIL_INVALID: 'Please enter a valid email address.',
    SUCCESS_TITLE: 'Verification Successful',
    SUCCESS_DESC: 'Your account has been activated. You can now log in.',
    FAILED_TITLE: 'Verification Failed',
    FAILED_DESC: 'We could not verify your email address. The link might be invalid.',
    EXPIRED_TITLE: 'Link Expired',
    EXPIRED_DESC: 'The verification link has expired. Please request a new one.',
    RESEND_TITLE: 'Resend Verification',
    RESEND_DESC: 'Enter your email address to receive a new verification link.',
    RESEND_SUCCESS: 'If an account exists, a new verification link has been sent.',
    LOADING_TEXT: 'Verifying your email address...',
    NETWORK_ERROR: 'Network Error: Please check your connection.',
    UNEXPECTED_ERROR: 'An unexpected error occurred.',
    ALREADY_VERIFIED: 'This account is already verified.',
    CONTINUE_LOGIN: 'Continue to Login',
    TRY_AGAIN: 'Try Again',
    REQUEST_NEW_LINK: 'Request New Link',
    RESEND_BUTTON: 'Send Verification Link',
  },
} as const;
