export const RESET_PASSWORD_CONSTANTS = {
  MESSAGES: {
    PASSWORD_REQUIRED: 'Password is required.',
    PASSWORD_TOO_SHORT: 'Password must be at least 12 characters long.',
    PASSWORD_UPPERCASE: 'Password must contain at least one uppercase letter.',
    PASSWORD_LOWERCASE: 'Password must contain at least one lowercase letter.',
    PASSWORD_NUMBER: 'Password must contain at least one number.',
    PASSWORD_SPECIAL: 'Password must contain at least one special character.',
    PASSWORD_MISMATCH: 'Passwords do not match.',
    CONFIRM_PASSWORD_REQUIRED: 'Please confirm your password.',
    SUCCESS_TITLE: 'Password Reset Complete',
    SUCCESS_DESC: 'Your password has been successfully updated. You can now log in with your new password.',
    ERROR_INVALID_TOKEN: 'The password reset link is invalid or has expired.',
    ERROR_MISSING_TOKEN: 'No reset token found. Please request a new password reset.',
    SUBMIT_BUTTON: 'Reset Password',
    BACK_TO_LOGIN: 'Back to Login',
    TITLE: 'Create New Password',
    SUBTITLE: 'Please enter your new password below.',
  },
} as const;
